### ISSUE TITLE
how can i run tjis coding

### ISSUE THREAD

**Issue by dinizikri** [priyankvora/POX_Controller-Load_Balancing#1]

**Comment by priyankvora** [comment]
you have to run pox controller in debug mode and create mininet topology with 6 host and 1 switch. I used openFlow protocol handler with ip_loadbalancer module. Make three nodes as Http Server and other three nodes as Http Clients which can generate http traffic using Curl. you will see the traffic pattern as expected in round robin or weight round robin if you provided weights.

**Comment by dinizikri** [comment]
tq for your reply
can u explain more about how to run cotroller in debug mode and how we can assign weight to server to handle

**Comment by dinizikri** [comment]
ubuntu@sdnhubvm:~[12:05]$ pox/pox.py log.level --DEBUG openflow.ip_loadbalancer_dynamic_weighted --ip=10.0.1.1 --servers=10.0.0.1,10.0.0.2,10.0.0.3
POX 0.5.0 (eel) / Copyright 2011-2014 James McCauley, et al.
Traceback (most recent call last):
  File "/home/ubuntu/pox/pox/boot.py", line 90, in do_import2
    __import__(name, level=0)
  File "/home/ubuntu/pox/pox/openflow/ip_loadbalancer_dynamic_weighted.py", line 169
    def _pick_server (self, key, inport):
    ^
IndentationError: unexpected indent
 
i cannot run this program and get this error
